name: "Install dependencies"
description: "Install dependencies"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: 3.8
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Hook version
      run: |
        echo -n ${VERSION_SUFFIX} >> VERSION
        echo "version = $(cat VERSION)"
      shell: bash
    - name: Install dependencies
      run: make install
      shell: bash
