name: "Install dependencies"
description: "Install dependencies"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: 3.8
  hook-version-file:
    description: "Hook version file (for pre-release version)"
  hook-version-suffix:
    description: "Version suffix (for re-release version)"
  makefile-target:
    description: "Makefile target"

runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Hook version
      if: ${{ inputs.hook-version-file }} && ${{ inputs.hook-version-suffix }}
      run: |
        echo -n ${{ inputs.hook-version-suffix }} >> ${{ inputs.hook-version-file }}
        echo "version = $(cat ${{ inputs.hook-version-file }})"
      shell: bash
    - name: Run makefile target (${{ inputs.makefile-target }})
      if: ${{ inputs.makefile-target }}
      run: make ${{ inputs.makefile-target }}
      shell: bash
